### ISSUE TITLE
API: add faucet balance endpoint

### ISSUE THREAD

**Issue by karacurt** [G7DAO/protocol#153]
**Problem:** We cannot see the faucet balance directly from the API
**Solution:** We need a `/balance` endpoint so we can check it

**Comment by gabrieltemtsen** [comment]
Hi @karacurt can i get assigned to this issue ?

**Comment by gabrieltemtsen** [comment]
https://github.com/G7DAO/protocol/pull/164

**Comment by gabrieltemtsen** [comment]
alright 👌🏼

**Comment by zomglings** [comment]
@gabrieltemtsen  - please check the review that @karacurt left for you on the PR. Let us continue all discussion on the PR.

**Comment by gabrieltemtsen** [comment]
Thanks @zomglings

**Comment by karacurt** [comment]
Solved by https://github.com/G7DAO/protocol/pull/164
