### ISSUE TITLE
`Burn amount exceeds balance` when trying to withdraw USDC from L2->L1

### ISSUE THREAD

**Issue by elclandestin0** [G7DAO/protocol#190]
To reproduce:

- Go to [staging](https://build.game7test.io)
- Navigate to Bridge
- Select Mainnet
- Select USDC
- Select Withdraw
- Select Arbitrum One in the `From` chain
- Try withdrawing an amount below or equal to your balance

Expected results:
![image](https://github.com/user-attachments/assets/b5f6002a-fcd9-4394-aa9a-d73a4b56c5cd)

To test locally, change `protocol` repo branch to `staging` and run `yarn dev` on `world-builder-dashboard`

**Comment by Anton-Mushnin** [comment]
#199
